#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Turns the local Flatpak manifest into the one a Flathub submission uses.

`io.github.josunlp.ephemeris.yml` builds from `type: dir`, which is right for
building a checkout you are looking at and is rejected for a submission:
Flathub builds a fixed revision, from a tag *and* the commit that tag points
at. A tag can be moved afterwards; the commit is what is actually pinned.

    python3 packaging/linux/flathub-manifest.py --tag v1.1.0

That writes `packaging/linux/flathub/` — the manifest with a `type: git`
source, and the `cargo-sources.json` belonging to the same revision. Copy both
into a checkout of `flathub/io.github.josunlp.ephemeris` and open the pull
request from there.

Which is the decision this script encodes: the submitted manifest is not a
second file kept in this repository. It is generated, so it cannot drift — and
generated from the pinned revision rather than from the working tree, so the
build commands submitted are the ones that revision actually carries. The only
manifest anybody edits is the local one, which is also the one CI's linter
invocations in its header refer to.

`--check` verifies without writing, which is worth running before tagging: it
answers "would this revision produce a submission at all", and its usual
failure is a `cargo-sources.json` that was not regenerated after `Cargo.lock`
changed.

Needs nothing but git and the standard library.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]

APP_ID = "io.github.josunlp.ephemeris"
MANIFEST = f"packaging/linux/{APP_ID}.yml"
SOURCES = "packaging/linux/cargo-sources.json"
LOCK = "Cargo.lock"

# Where Flathub fetches the revision from. `type: git` needs a URL that is
# reachable without credentials, so the HTTPS form rather than the SSH one.
URL = "https://github.com/JosunLP/Ephemeris.git"

OUT = HERE / "flathub"

# The source stanza this replaces. Matched rather than assumed: a manifest that
# no longer builds from a directory has been changed in a way that invalidates
# what is below, and stopping is better than silently submitting the wrong
# thing.
DIR_SOURCE = re.compile(r"^(?P<indent> *)- type: dir$", re.MULTILINE)


def git(*arguments: str) -> str:
    """Run git in the repository and return its output, or stop."""
    done = subprocess.run(
        ["git", "-C", str(ROOT), *arguments],
        capture_output=True,
        text=True,
    )
    if done.returncode != 0:
        sys.exit(f"git {' '.join(arguments)}: {done.stderr.strip()}")
    return done.stdout


def resolve(tag: str) -> str:
    """The commit `tag` points at, following an annotated tag to its object."""
    if not git("tag", "--list", tag).strip():
        sys.exit(
            f"there is no tag {tag} in this repository — fetch it, or tag the "
            "revision you mean to submit first"
        )
    # `rev-list -n 1` peels an annotated tag; `rev-parse` would give the tag
    # object's own hash, which is not a commit and not what Flathub wants.
    return git("rev-list", "-n", "1", tag).strip()


def at(commit: str, path: str) -> str:
    """A file as it was at `commit`."""
    return git("show", f"{commit}:{path}")


def cargo_sources_module():
    """`cargo-sources.py`, imported despite the dash in its name."""
    spec = importlib.util.spec_from_file_location(
        "cargo_sources", HERE / "cargo-sources.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def git_source(indent: str, tag: str, commit: str) -> list[str]:
    """The `type: git` stanza, at the same indentation as what it replaces."""
    inner = indent + "  "
    return [
        f"{indent}# Flathub builds a fixed revision rather than a checkout,",
        f"{indent}# and both halves of it: a tag can be moved afterwards, so",
        f"{indent}# the commit is what is actually pinned.",
        f"{indent}#",
        f"{indent}# This file is generated by",
        f"{indent}# `packaging/linux/flathub-manifest.py` from the manifest as",
        f"{indent}# it stands at that commit. Edit that one, not this one.",
        f"{indent}- type: git",
        f"{inner}url: {URL}",
        f"{inner}tag: {tag}",
        f"{inner}commit: {commit}",
    ]


def submission(manifest: str, tag: str, commit: str) -> str:
    """`manifest` with its directory source replaced by a pinned git one."""
    lines = manifest.splitlines()
    found = DIR_SOURCE.search(manifest)
    if not found:
        sys.exit(
            f"{MANIFEST} at {commit[:12]} has no `- type: dir` source — it has "
            "been changed in a way this script does not know how to submit"
        )

    indent = found.group("indent")
    start = manifest[: found.start()].count("\n")

    # The stanza runs to the next line that is no deeper than the `- ` marker.
    # The comments in front of `cargo-sources.json` sit at the marker's own
    # indentation and so are kept, which is right — they describe that source,
    # not this one.
    end = start + 1
    while end < len(lines):
        line = lines[end]
        if line.strip() and not line.startswith(indent + " "):
            break
        end += 1

    return "\n".join(
        lines[:start] + git_source(indent, tag, commit) + lines[end:]
    ) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tag",
        required=True,
        help="the release tag to submit, e.g. v1.1.0",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the revision could be submitted, without writing anything",
    )
    args = parser.parse_args()

    commit = resolve(args.tag)
    manifest = at(commit, MANIFEST)
    sources = at(commit, SOURCES)

    # The crate list is generated from `Cargo.lock`, and the submitted build
    # has no network to notice it is wrong: a mismatch here means the Flathub
    # build fails to fetch a crate, or fetches a version the lock file does not
    # name. CI checks this on every push; it is checked again for the revision
    # being submitted, because that is the one that matters and it may be
    # older than the branch.
    module = cargo_sources_module()
    crates = module.packages(at(commit, LOCK))
    expected = json.dumps(module.sources(crates), indent=4) + "\n"
    if sources != expected:
        sys.exit(
            f"{SOURCES} at {args.tag} is out of step with {LOCK} at the same "
            "revision — that revision cannot be submitted; regenerate with "
            "packaging/linux/cargo-sources.py, tag again, and rerun this"
        )

    pinned = submission(manifest, args.tag, commit)

    # A tag that is behind the working tree is legitimate — you submit a
    # release, not a branch — but it is also how you end up submitting a
    # manifest you have since fixed, so it is said out loud rather than left
    # to be noticed.
    if (ROOT / MANIFEST).read_text(encoding="utf-8") != manifest:
        print(
            f"note: {MANIFEST} differs between {args.tag} and the working "
            "tree; the submission follows the tag.",
            file=sys.stderr,
        )

    if args.check:
        print(
            f"{args.tag} ({commit[:12]}) can be submitted — "
            f"{len(crates)} crates, in step with {LOCK}"
        )
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{APP_ID}.yml").write_text(pinned, encoding="utf-8")
    (OUT / "cargo-sources.json").write_text(sources, encoding="utf-8")
    print(f"wrote {(OUT / f'{APP_ID}.yml').relative_to(ROOT)}")
    print(f"wrote {(OUT / 'cargo-sources.json').relative_to(ROOT)}")
    print(f"pinned to {args.tag} at {commit}")
    print(
        "\nCopy both into a checkout of "
        f"flathub/{APP_ID} and open the pull request there. Lint the pair "
        "first:\n"
        "    flatpak run --command=flatpak-builder-lint org.flatpak.Builder \\\n"
        f"        manifest packaging/linux/flathub/{APP_ID}.yml"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
